name: 'deploy when push'

on:
  push:
    branches: [feat_docker]
  pull_request:
    branches: [feat_docker]

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/web37-ZelloDraw/ && git pull origin feat_docker
            docker build -f Dockerfile -t zelloDraw .
            docker ps -a -q --filter name=zelloDraw | grep -q . && docker rm -f zelloDraw
            docker run -d -p 3000:3000 -p 19785:19785 --name zelloDraw zelloDraw
